title: Flyxiv Blog 
description: Personal Studies and Projects 
theme: just-the-docs

url: https://junyeopN.github.io/blog

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
